config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  resources :flights
  resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arrivals, class_name: "Flight", foreign_key: "arrival_airport_id"
  has_many :departures, class_name: "Flight", foreign_key: "departure_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  belongs_to :flights, required: false 
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :arrival_airport, class_name: 'Airport', foreign_key: "arrival_airport_id"
  belongs_to :departure_airport, class_name: 'Airport', foreign_key: "departure_airport_id"
  has_many :bookings
  has_many :passengers
  scope :departing,  ->  (code)  { where(departure_airport_id: code) }
  scope :arrivaling, ->  (code)  { where(arrival_airport_id: code) }
  scope :leave_day,  ->  (date)  { where(start: date.to_date.all_day) }
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking, required: false, inverse_of: :passenger, foreign_key: "booking_id"
  belongs_to :flight,  required: false, inverse_of: :passenger 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new(booking_params)
    @flight = Flight.find(params[:booking][:flight])
    @num_passengers = params[:booking][:passengers]
  end

  def create 
    @booking = Booking.new(booking_params)
    if @booking.save 
      flash[:info] = "Booking confirmed"
      redirect_to booking_path(@booking)
    else 
      flash.now[:error] = "Details incorrect"
    end 
  end 

  def show 
    @booking = Booking.find_by_id(params[:id])
  end 

  private 
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:flight_id, :name, :email])
    end 
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  
  def index 
    @departure_airports = Airport.all.map{ |u| [u.name, u.id] }
    @arrival_airports = Airport.all.map{ |u| [u.name, u.id] }
    @passengers = [[1,1],[2,2],[3,3],[4,4]]
    @last_date = Flight.maximum(:start).to_date
    @flight_date = @first_date = Flight.minimum(:start).to_date 

    if search = params[:flights]
      @departure = search[:departure_airport_id]
      @arrival   = search[:arrival_airport_id]
      @leave_date = search[:leaving_date]
      @passenger = search[:passengers]
      
      @search_result = Flight.departing(search[:departure_airport_id]).arrivaling(search[:arrival_airport_id]).leave_day(
                       search[:leaving_date])
    end 
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div class='container'>
<h1>Bookings</h1>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<div class='form-row align-item-center'>
<div class='col-md-8'>
<%= form_for(@booking) do |f| %>
  <h5>Flight Details:</h5>
  <%= f.label :flight, "#{@flight.id},
                        #{@flight.departure_airport.name},
                        #{@flight.arrival_airport.name},
                        #{@flight.start}" %>
  <%= f.hidden_field :flight_id, :value => @flight.id %>
  </br>
  <% num = 0 %>
  <% @num_passengers.to_i.times do %>
    <%= f.fields_for :passengers, Passenger.new do |p| %>
      <%= p.label :passenger, "Passenger #{num += 1}:" %></br>
      <%= p.label :name %>
      <%= p.text_field :name, class: 'form-control' %></br>
      <%= p.label :email %>
      <%= p.email_field :email, class: 'form-control' %></br>
      <%= p.hidden_field :flight_id, :value => @flight.id %>
    <% end %>
  <% end %>
  <%= f.submit "Book", class:'btn btn-primary' %>
<% end %>
</div>
</div>
</div>

app/views/bookings/show.html.erb
<h1>Booking info</h1>

<div> 
   Flight Id: <%= @booking.flight_id %>
      <% @booking.passengers.each do |p| %>
        <li>
          Name: <%= p.name %> (Email: <%= p.email %>)
        </li>
      <% end %> 
</div>

app/views/flights/index.html.erb
<div class='container'>
<h1>Flight Bookings</h1>
<div class="row">
<div class="col-sm">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <h3>Search for flights</h3>
  <%= form_for("flights", method: "get") do |f| %>
    <%= f.label :departure %>
    <%= f.select(:departure_airport_id, @departure_airports,{}, {:class => 'form-control'}) %></br>

    <%= f.label :arrival %>
    <%= f.select(:arrival_airport_id, @arrival_airports,{}, {class:'form-control'}) %></br>

    <%= f.label :passengers %>
    <%= f.select(:passengers, @passengers,{}, {class:'form-control'}) %></br>
  
    <%= f.label :date %>
    <%= date_field_tag('flights[leaving_date]', value = @flight_date, 
                        min: @first_date, max: @last_date, class:'form-control') %> 
  </br>
    <%= f.submit "Search", class: 'btn btn-primary' %>
  <% end %>
</div> 
</br>
<div class='col-sm'>
  <% if search = params[:flights] %>
    <%= form_for('booking', url: new_booking_url, method: :get) do |f| %>
      <h3><%= f.label :results, 'Search Results:'%></h3></br>
      <% @search_result.each do |flight| %>
        <%= f.label :flight, "#{flight.departure_airport.name},
                              #{flight.arrival_airport.name},
                              #{flight.start}"%>
        <%= f.radio_button :flight, flight.id, checked: true %>
      </br>
      <% end %>
      <%= f.hidden_field :passengers, :value => @passenger %></br>
      <%= f.submit "Search", class: 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>
</div>
</div>

app/views/layouts/_header.html.erb
<div class= 'navbar navbar-nav navbar-dark bg-dark' >
  <%= link_to 'Home', root_url, class: 'navbar-brand' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>